[build-system]
requires = [
    "setuptools>=69",
    "wheel",
    "build"
]
build-backend = "setuptools.build_meta"

[project]
name = "CADET-GUI"
dynamic = ["version"]
authors = [
    { name = "Hannah Lanzrath", email = "h.lanzrath@fz-juelich.de" },
    { name = "Johannes Schmölder", email = "j.schmoelder@fz-juelich.de" }
]
description = ""
readme = "README.md"
requires-python = ">=3.10"
keywords = ["process modeling", "process optimization", "chromatography"]
license = { text = "GPLv3" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Intended Audience :: Science/Research",
]
dependencies = [
]

[dependency-groups]
testing = [
    "coverage",
    "pytest",
    "pytest-cov"
]
docs = [
    "myst-nb>=0.17.1",
    "numpydoc>=1.5.0",
    "sphinx>=5.3.0",
    "sphinxcontrib-bibtex>=2.5.0",
    "sphinx_book_theme>=1.0.0",
    "sphinx_copybutton>=0.5.1",
    "sphinx-sitemap>=2.5.0",
]
dev = [
    {include-group = "docs"},
    {include-group = "testing"},
    "certifi", # tries to prevent certificate problems on windows
    "pre-commit",
    "ruff"
]

[tool.ruff]
src = ["CADET-GUI", "tests"]
exclude = []
line-length = 88
fix = true

[tool.ruff.lint]
preview = true
select = [
  "ANN",  # type annotations
  "D",    # docstrings
  "E",    # pycodestyle errors
  "F",    # pyflakes
  "W",    # pycodestyle warnings
  "I",    # isort
]
ignore = [
  "ANN401",  # Allow dynamically typed expressions like `Any`
  "D100",    # Allow missing docstring in public module
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.pycodestyle]
max-line-length = 100

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = [
  "ANN",   # type annotations
  "D",     # docstrings
  "E402",  # imports on top of module 
  "E731",  # lamba assignments
  "F841",  # unused variables
]


[tool.pytest.ini_options]
testpaths = [
    "tests",
]
pythonpath = [
    "tests",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
