"""Generate synthetic example data for examples/data/characterization/.

Every file here is generated by running a real CADET-Process simulation
through the exact process CharacterizationWorkbenchWidget()'s own defaults
build (LRMP column, SMA binding, LC system with the periphery units on),
with one or two "true" parameter values deliberately changed from those
defaults, then sampling and adding noise. None of it is measured data --
see examples/EXAMPLE_DATA.md for the same convention already used for
ParameterEstimationWidget's own example files.

Re-run this script to regenerate everything:
    python3 examples/generate_characterization_example_data.py
"""
from __future__ import annotations

import warnings
from pathlib import Path

import numpy as np

warnings.filterwarnings("ignore")

from cadetgui.cadetprocessadapter import BINDING_MODELS, COLUMN_MODELS  # noqa: E402
from cadetgui.simulation import run_process  # noqa: E402
from cadetgui.widgets.composite import (  # noqa: E402
    ConfigurationWidget,
    InstrumentWidget,
)

OUT_DIR = Path(__file__).parent / "data" / "characterization"
SIGNAL_UNIT, SIGNAL_PORT = "outlet", "inlet"  # matches classify_signal_ports' default pick


def base_process() -> object:
    """CharacterizationWorkbenchWidget()'s own default process, built the same way."""
    iw = InstrumentWidget()
    cw = ConfigurationWidget(instrument=iw)
    for unit in ("tubing_pre_injection", "tubing_detectors", "mixer"):
        iw._unit_checkboxes[unit].value = True
    cw._column_picker.value = COLUMN_MODELS["Lumped Rate Model With Pores (LRMP)"]
    cw._binding_picker.value = BINDING_MODELS["Steric Mass Action (SMA)"]
    return cw.process


def save_csv(path: Path, time_min: np.ndarray, signal: np.ndarray) -> None:
    """Write a `time_min,signal` CSV -- the exact shape DataImportWidget reads."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write("time_min,signal\n")
        for t, s in zip(time_min, signal):
            f.write(f"{t:.6f},{s:.8f}\n")
    print(f"wrote {path}")


def noisy_signal(process: object, *, scale: float, seed: int) -> tuple[np.ndarray, np.ndarray]:
    """Simulate `process`, sample its outlet signal, and add Gaussian noise."""
    result = run_process(process)
    solution = result.solution[SIGNAL_UNIT][SIGNAL_PORT]
    time_min = solution.time / 60.0
    signal = solution.solution[:, 0].copy()
    rng = np.random.default_rng(seed)
    signal += rng.normal(0.0, scale * max(signal.max(), 1e-12), size=signal.shape)
    np.clip(signal, 0.0, None, out=signal)
    return time_min, signal


def main() -> None:
    """Generate every file under examples/data/characterization/."""
    # --- Periphery: pre-injection tubing -----------------------------------
    # Changed from InstrumentWidget's own seed defaults (length=0.1,
    # axial_dispersion=1e-7): length=0.35, axial_dispersion=8e-7.
    process = base_process()
    process.flow_sheet.tubing_pre_injection.length = 0.35
    process.flow_sheet.tubing_pre_injection.axial_dispersion = [8e-7]
    t, s = noisy_signal(process, scale=0.01, seed=20260924_01)
    save_csv(OUT_DIR / "periphery_pre_injection.csv", t, s)

    # --- Periphery: detector tubing ------------------------------------------
    # Changed: length=0.22, axial_dispersion=5e-7 (default: 0.1 / 1e-7).
    process = base_process()
    process.flow_sheet.tubing_detectors.length = 0.22
    process.flow_sheet.tubing_detectors.axial_dispersion = [5e-7]
    t, s = noisy_signal(process, scale=0.01, seed=20260924_02)
    save_csv(OUT_DIR / "periphery_detectors.csv", t, s)

    # --- Pre-injection + mixer ------------------------------------------------
    # Changed: tubing_pre_injection.length=0.35 (as above), mixer volume=3e-6
    # (default: 1e-6).
    process = base_process()
    process.flow_sheet.tubing_pre_injection.length = 0.35
    process.flow_sheet.mixer.init_liquid_volume = 3e-6
    t, s = noisy_signal(process, scale=0.01, seed=20260924_03)
    save_csv(OUT_DIR / "pre_injection_mixer.csv", t, s)

    # --- Bed: two replicate-style tracer pulses -------------------------------
    # Changed from ConfigurationWidget's LRMP defaults (bed_porosity=0.72,
    # axial_dispersion=1e-8): bed_porosity=0.38, axial_dispersion=6e-8 -- a
    # more physically typical packed-bed porosity, clearly different from
    # the default so fitting is meaningful.
    for i, seed in enumerate((20260924_04, 20260924_05)):
        process = base_process()
        process.flow_sheet.column.bed_porosity = 0.38
        process.flow_sheet.column.axial_dispersion = [6e-8]
        t, s = noisy_signal(process, scale=0.015, seed=seed)
        save_csv(OUT_DIR / f"bed_replicate_{i}.csv", t, s)

    # --- Particles: film diffusion --------------------------------------------
    # Changed: film_diffusion=2e-5 (default: 1e-3) -- a more physically
    # typical order of magnitude, and clearly different from the default.
    process = base_process()
    process.flow_sheet.column.film_diffusion = [2e-5]
    t, s = noisy_signal(process, scale=0.015, seed=20260924_06)
    save_csv(OUT_DIR / "particles.csv", t, s)

    # --- Adsorption: rapid-equilibrium SMA ------------------------------------
    # The default binding model has capacity=0/characteristic_charge=0/
    # adsorption_rate=0 (nothing binds at all), so all three are set here,
    # in rapid-equilibrium mode (is_kinetic=False, desorption_rate=1) to
    # match CharacterizeAdsorptionParameters(is_kinetic=False)'s own
    # assumption: characteristic_charge=5.0, adsorption_rate=2.0 (the
    # equilibrium constant directly in this mode), capacity=1200.0.
    process = base_process()
    bm = process.flow_sheet.column.binding_model
    bm.is_kinetic = False
    bm.characteristic_charge = [5.0]
    bm.adsorption_rate = [2.0]
    bm.desorption_rate = [1.0]
    bm.capacity = 1200.0
    t, s = noisy_signal(process, scale=0.015, seed=20260924_07)
    save_csv(OUT_DIR / "adsorption.csv", t, s)

    # --- Capacity ---------------------------------------------------------------
    # Same rapid-equilibrium setup as adsorption.csv (capacity fitting needs
    # a real characteristic_charge/adsorption_rate to bind against too), just
    # a different capacity: 900.0 instead of 1200.0.
    process = base_process()
    bm = process.flow_sheet.column.binding_model
    bm.is_kinetic = False
    bm.characteristic_charge = [5.0]
    bm.adsorption_rate = [2.0]
    bm.desorption_rate = [1.0]
    bm.capacity = 900.0
    t, s = noisy_signal(process, scale=0.015, seed=20260924_08)
    save_csv(OUT_DIR / "capacity.csv", t, s)


if __name__ == "__main__":
    main()
